name: CI Frontend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Dependencies and Build
      run: |
        npm install
        npm run build

    - name: Archive Build
      run: |
        mkdir -p build
        cp -r build/* build/

    - name: Upload Artifact to Jenkins
      run: |
        scp -o StrictHostKeyChecking=no -i ${{ secrets.JENKINS_SSH_KEY }} \
        -r ./build/ ${JENKINS_USER}@<JENKINS_IP>:/var/jenkins_home/frontend-artifacts/

      env:
        JENKINS_USER: ${{ secrets.JENKINS_USER }}
